version: '3.4'

# Common Django template for GeoNode and Celery services below
x-common-django:
  &default-common-django
  image: becamexidc2020/geoportal_django:3.3.2
  restart: on-failure
  env_file:
    - .env
  volumes:
    - '.:/usr/src/geonode'

services:

  # Our custom django application. It includes Geonode.
  django:
    << : *default-common-django

  # Celery worker that executes celery tasks created by Django.
  celery:
    << : *default-common-django
    container_name: celery4${COMPOSE_PROJECT_NAME}
    depends_on:
      - django
    environment:
      - IS_CELERY=True
    entrypoint: ["/usr/src/geonode/entrypoint.sh"]
    command: "celery-cmd"

  # Nginx is serving django static and media files and proxies to django and geonode
  geonode:
    image: becamexidc2020/geoportal_nginx:3.3.2

  # Removes letsencrypt when developing
  letsencrypt:
    image: becamexidc2020/geoportal_letsencrypt:3.3.2
    deploy:
      replicas: 0
