version: '3.4'

services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=https://geoportal-uat.vntts.vn
      - GEONODE_LB_PORT=80
      - SITEURL=https://geoportal-uat.vntts.vn/
      - ALLOWED_HOSTS=['*', ]
      - GEOSERVER_PUBLIC_LOCATION=https://geoportal-uat.vntts.vn/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=https://geoportal-uat.vntts.vn/geoserver/

  celery:
    build: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=https://geoportal-uat.vntts.vn
      - GEONODE_LB_PORT=80
      - SITEURL=https://geoportal-uat.vntts.vn/
      - ALLOWED_HOSTS=['*', ]
      - GEOSERVER_PUBLIC_LOCATION=https://geoportal-uat.vntts.vn/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=https://geoportal-uat.vntts.vn/geoserver/

  geonode:
    environment:
      - HTTP_HOST=geoportal-uat.vntts.vn

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=https://geoportal-uat.vntts.vn
      - GEONODE_LB_PORT=80
  #    - NGINX_BASE_URL=