version: '3.4'

services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=geoportal-uat.vntts.vn
      - GEONODE_LB_PORT=80
      - SITEURL=https://geoportal-uat.vntts.vn/
      - ALLOWED_HOSTS=['*', ]
      - GEOSERVER_PUBLIC_LOCATION=https://geoportal-uat.vntts.vn/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=https://geoportal-uat.vntts.vn/geoserver/
    networks:
      - geonode_db_shared
      - geoportal33_net

  celery:
    build: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=geoportal-uat.vntts.vn
      - GEONODE_LB_PORT=80
      - SITEURL=https://geoportal-uat.vntts.vn/
      - ALLOWED_HOSTS=['*', ]
      - GEOSERVER_PUBLIC_LOCATION=https://geoportal-uat.vntts.vn/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=https://geoportal-uat.vntts.vn/geoserver/
    networks:
      - geonode_db_shared
      - geoportal33_net

  geonode:
    environment:
      - HTTP_HOST=geoportal-uat.vntts.vn
    networks:
     - geoportal33_net
     - npm_network

  pg_tileserv:
    networks:
      - geoportal33_net

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=geoportal-uat.vntts.vn
      - GEONODE_LB_PORT=80
  #    - NGINX_BASE_URL=
    networks:
      - geonode_db_shared
      - geoportal33_net
  geoserver2:
    environment:
      - GEONODE_LB_HOST_IP=geoportal-uat.vntts.vn
      - GEONODE_LB_PORT=80
  #    - NGINX_BASE_URL=
    networks:
      - geonode_db_shared
      - geoportal33_net

  rabbitmq:
    networks:
      - geoportal33_net

networks:
  geoportal33_net:

  npm_network:
    external: true
    
  geonode_db_shared:
    external: true
  